# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'CampusEats' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'JTAppleCalendar', '~> 6.0'

  # Pods for Calendar
  
  pod 'JTAppleCalendar', '~> 6.0'

  # Pods to show Images asynchrnously
  pod 'SDWebImage/WebP'

end
