# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CampusEats' do

  use_frameworks!

  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end
